### ISSUE TITLE
Add support for Mouse

### ISSUE THREAD

**Issue by d9705996** [torrentalle/vscode-perl-moose#1]
The current syntax regular expressions do not include support for [Mouse](https://metacpan.org/pod/Mouse)

Mouse has the same syntax as Mouse and Moo and I have tested in VSCode changing `use Mouse; ` to `use Moose` and syntax is higlighted correctly.

**Comment by torrentalle** [comment]
Thanks for your contribution.

After some pending tests, I'll publish new release to Visual Studio Marketplace

**Comment by torrentalle** [comment]
New release is published into marketplace.
